spring.application.name=Jewelry-shop-Backend

server.port=8080

# --- PostgreSQL DataSource ---
#Real credentials received from another file.
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL_FLAG}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL_FLAG}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.default_schema=public

# --- Flyway ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=true
# Remove/Comment out below for prod
spring.flyway.clean-disabled=true
#spring.flyway.clean-disabled=false

# --- Devtools ---
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

# --- Media storage (local or s3) ---
storage.type=${STORAGE_TYPE:local}
# When type=local, absolute OS path where files live
storage.local.base-path=${STORAGE_LOCAL_BASE_PATH:}
# Public base URL used to serve media
# local example: http://localhost:8080/files/
# s3/cdn example: https://cdn.example.com/
storage.public-base-url=${STORAGE_PUBLIC_BASE_URL:}

# --- Logging ---
logging.level.andreas.kafkis.eberle.jewelry.shop.backend=DEBUG
logging.level.org.springframework.web=DEBUG
logging.file.name=logs/jewelry-shop.log

# --- Metrics (Actuator) ---
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.metrics.export.prometheus.enabled=true